# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: TrueBoolParam
    type: boolean
    default: true

variables:
  - name: TrueBool
    value: true

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- ${{ if eq(variables.TrueBool, 'true') }}:
  - script: |
      echo String True Equals
    displayName: 'StringTrueEquals'

- ${{ if eq(variables.TrueBool, true) }}:
  - script: |
      echo Bool True Equals
    displayName: 'BoolTrueEquals'

- ${{ if eq(parameters.TrueBoolParam, 'true') }}:
  - script: |
      echo String True Equals Param
    displayName: 'StringTrueEqualsParam'

- ${{ if eq(parameters.TrueBoolParam, true) }}:
  - script: |
      echo Bool True Equals Param
    displayName: 'BoolTrueEqualsParam'

- ${{ if eq('${{ parameters.TrueBoolParam }}', 'true') }}:
  - script: |
      echo String True Equals Param2
    displayName: 'StringTrueEqualsParam2'

- ${{ if eq('${{ parameters.TrueBoolParam }}', true) }}:
  - script: |
      echo Bool True Equals Param2
    displayName: 'BoolTrueEqualsParam2'
